### ISSUE TITLE
Getting an error with sysmon

### ISSUE THREAD

**Issue by rangerrkm** [ahmedkhlief/APT-Hunter#11]
Hello,

I'm getting this error:

File "APT-Hunter.py", line 108, in evtxdetect
    EvtxDetection.detect_events_Sysmon_log(sysmon_path)
  File "C:\IR\APT-Hunter-main-Windows-V1.1-Stable\lib\EvtxDetection.py", line 2018, in detect_events_Sysmon_log
    if CommandLine[0].strip().find(i)>-1:
IndexError: list index out of range

Using python 3.7.4 and Sysmon 13.02

Command: python APT-Hunter.py -t evtx --sysmon c:/temp3/logs/wineventlog/Sysmon.evtx -o Test_00

Thanks,

**Comment by ahmedkhlief** [comment]
A lot changed since April , kindly check and let me know if the issue still exist
