### ISSUE TITLE
some questions about summary

### ISSUE THREAD

**Issue by MangoYou** [ahmedkhlief/APT-Hunter#12]
there is one of the security log that I see in the report xlsx , so why I see the Security Authentication Summary have lots of data in that.
![image](https://user-images.githubusercontent.com/32865250/128139032-738d3255-05b3-43f7-914b-20973857e7ee.png)

![image](https://user-images.githubusercontent.com/32865250/128138991-fba9049b-45ed-46d5-b442-4a546180b030.png)

**Comment by ahmedkhlief** [comment]
The summary for logon events . the new version will provide a seprate report for logon events . i will release it tonight .
