### ISSUE TITLE
2.0 some errors (CommandLine[0].strip().find("*certutil* , RuntimeError: Failed to parse chunk header)

### ISSUE THREAD

**Issue by chourete** [ahmedkhlief/APT-Hunter#14]
**windows 10, python 3.7.9**
**because errors , in the report, sysmon missed a lot of important information**
**The same error occurs regardless of the execution of python or exe**
**thx you very much, this tool is really useful, it reduces the investigation time!!**

----------------------------------------

Error Analyzing Security logs
ERROR:root:Traceback (most recent call last):
  File "./APT-Hunter.py", line 64, in evtxdetect_auto
    EvtxDetection.detect_events_security_log(Security_path_list,input_timezone)
  File "C:\Users\User\Desktop\APT2.0\lib\EvtxDetection.py", line 255, in detect_events_security_log
    for record in parser.records():
**RuntimeError: Failed to parse chunk header**

Error Analyzing Powershell logs
ERROR:root:Traceback (most recent call last):
  File "./APT-Hunter.py", line 88, in evtxdetect_auto
    EvtxDetection.detect_events_powershell_log(powershell_path_list,input_timezone)
  File "C:\Users\User\Desktop\APT2.0\lib\EvtxDetection.py", line 2425, in detect_events_powershell_log
    for record in parser.records():
**RuntimeError: Failed to parse chunk header**

Error Analyzing Sysmon logs
ERROR:root:Traceback (most recent call last):
  File "./APT-Hunter.py", line 130, in evtxdetect_auto
    EvtxDetection.detect_events_Sysmon_log(sysmon_path_list,input_timezone)
  File "C:\Users\User\Desktop\APT2.0\lib\EvtxDetection.py", line 3345, in detect_events_Sysmon_log
    **CommandLine[0].strip().find("*certutil*script\\:http\\[\\:\\]\\/\\/*")>-1 or**
**IndexError: list index out of range**

Time Sketch Report saved as win_TimeSketch.csv
Logon Events Report saved as win_Logon_Events.csv
**./APT-Hunter.py:263: FutureWarning: Use of **kwargs is deprecated, use engine_kwargs instead.
  writer = pd.ExcelWriter(Report, engine='xlsxwriter', options={'encoding': 'utf-8'})**
Report saved as win_Report.xlsx

**Comment by ahmedkhlief** [comment]
Hi , Please check the new release (V3.0)
