### ISSUE TITLE
executable only process folder named Logs

### ISSUE THREAD

**Issue by tamermh** [ahmedkhlief/APT-Hunter#21]
apt-unter is working ok when folder of the logs is "**Logs**" as the following

C:\tools\APT-HunterV2.0-Stable+>APT-Hunter.exe -p **\Logs\** -o project3

**But** if i changed to anything else for example

C:\tools\APT-HunterV2.0-Stable+>APT-Hunter.exe -p **\Log\** -o project3

it shows the following and all excel are created and empty

**Issue with the path**

**Comment by ahmedkhlief** [comment]
Hi Please check the new release ( V3.0 )
