### ISSUE TITLE
Timezone won't change

### ISSUE THREAD

**Issue by adabiraihan** [ahmedkhlief/APT-Hunter#26]
Hi Dev,

I think there's an error with the -tz/--timezone args, the timezone still +00:00 whenever I set local / (Asia/Jakarta)

**Comment by sakiro** [comment]
This is a problem about dateutil.tz isn't use pytz object.
You can install tzlocal 
https://pypi.org/project/tzlocal/
Modify original APT-Hunter.py
-------
from tzlocal import get_localzone

replace 
input_timezone = tz.tzlocal()
to 
input_timezone=get_localzone()

It is useful for me.

**Comment by adabiraihan** [comment]
Hi Sakiro,

Thanks for replying, I already tried that but no luck.

May I know what argument did you use?  
is it :
1. -tz local
2. No argument (default: local)
3. Specified the location "-tz Asia/Bangkok"

Thanks

**Comment by sakiro** [comment]
I just modify default option. Choose 2 No argument.

**Comment by ahmedkhlief** [comment]
Thank you for reporting , Fixed in 3.2 .
