### ISSUE TITLE
Hello, two problems occur in APT-hunter.py when i use option --allreport. This problem is XlsxWriter change his parameter and mehod.

### ISSUE THREAD

**Issue by sakiro** [ahmedkhlief/APT-Hunter#28]
Hello, two problems occur in APT-hunter.py when i use option --allreport. This problem is XlsxWriter change his parameter and mehod.
I try to modify original code to fix it.
problem 1
![problem1](https://github.com/ahmedkhlief/APT-Hunter/assets/3309932/cb1ebdb9-efab-4c56-8534-58a709c7bc13)
original code 1
writer = pd.ExcelWriter(Report, engine='xlsxwriter', options={'encoding': 'utf-8'})
modify code 1
writer = pd.ExcelWriter(Report, engine='xlsxwriter')
problem 2 (after fix problem 1)
![problem2](https://github.com/ahmedkhlief/APT-Hunter/assets/3309932/ccfbdc4f-9d67-4b12-97be-7721b514429e)

orginal code 2
writer.save()
modify code 2
writer.close()

using python 3.11.2
Package         Version
--------------- -------
evtx            0.8.2
netaddr         0.8.0
numpy           1.24.3
pandas          2.0.1
pip             23.0.1
python-dateutil 2.8.2
pytz            2023.3
setuptools      67.6.0
six             1.16.0
tzdata          2023.3
wheel           0.40.0
XlsxWriter      3.1.0

_Originally posted by @sakiro in https://github.com/ahmedkhlief/APT-Hunter/issues/27#issuecomment-1588614470_

**Comment by Lq0ne** [comment]
I got the first error too. Have you solved this problem?

**Comment by sakiro** [comment]
After modify the APT-hunter.py, it;s gone.

**Comment by ahmedkhlief** [comment]
Hi !
I will resolve the issue in the next few days

**Comment by ahmedkhlief** [comment]
i pushed the fix ! please check and let me know . thanks sakiro !

**Comment by ahmedkhlief** [comment]
Thank you for reporting , Fixed in 3.2 .
