### ISSUE TITLE
File path does not exist

### ISSUE THREAD

**Issue by clive7391** [ahmedkhlief/APT-Hunter#9]
I am trying this out during post-mortem forensics.

I copy all .evtx files out of my images into a folder and then run APT-Hunter against all the files in the folder.

Only the System and Security Events parse and I receive the following errors running the following command:
.\APT-Hunter.exe -t evtx -p I:\Evidence\Case\EVTX\Dc1\ -o Case-Dc1

Error Analyzing Security logs: File Path Does Not Exist
Error Analyzing System logs : File Path Does Not Exist
Error Analyzing Powershell Operational logs : File Path Does Not Exist
Error Analyzing Powershell logs : File Path Does Not Exist
Error Analyzing TerminalServices LocalSessionManager logs: File Path Does Not Exist
Error Analyzing Scheduled Task logs : File Path Does Not Exist
Error Analyzing Windows Defender logs : File Path Does Not Exist
Error Analyzing WinRM logs : File Path Does Not Exist
Error Analyzing Sysmon logs

Does it have anything to do with the the filenames from the OS?
Microsoft-Windows-PowerShell%4Admin.evtx
Microsoft-Windows-PowerShell%4Operational.evtx
Microsoft-Windows-TerminalServices-LocalSessionManager%4Admin.evtx
Microsoft-Windows-TerminalServices-LocalSessionManager%4Operational.evtx
Microsoft-Windows-Windows Defender%4Operational.evtx
Microsoft-Windows-Windows Defender%4WHC.evtx

**Comment by ahmedkhlief** [comment]
Hi , if you didn't use the powershell script to extract the logs then you
need to use the argument for each log type as the file names is not the
same with output from the script . -p only should be used with output of
the default powershell script . I will try to create smart log type
detection to detect logs with different names .

**Comment by clive7391** [comment]
I did this and it works mostly.

cp Microsoft-Windows-PowerShell%4Operational.evtx Powershell_Operational.evtx
cp “Windows PowerShell.evtx” Windows_PowerShell.evtx
cp Microsoft-Windows-TerminalServices-LocalSessionManager%4Operational.evtx  LocalSessionManager.evtx
cp Microsoft-Windows-TaskScheduler%4Operational.evtx TaskScheduler.evtx
cp ‘Microsoft-Windows-Windows Defender%4Operational.evtx’ Windows_Defender.evtx
cp Microsoft-Windows-WinRM%4Operational.evtx  WinRM.evtx
cp Microsoft-Windows-Sysmon%4Operational  Sysmon.evtx

except
Error Analyzing WinRM logs 
ERROR:root:Traceback (most recent call last):
  File "APT-Hunter.py", line 99, in evtxdetect
    EvtxDetection.detect_events_Microsoft_Windows_WinRM(winrm_path)
  File "/home/sansforensics/APT-Hunter/lib/EvtxDetection.py", line 1934, in detect_events_Microsoft_Windows_WinRM
    Event_desc="User ("+User_ID[0].strip()+") Connected to ("+ Connection[0].strip() +") using WinRM - powershell remote "
AttributeError: 'tuple' object has no attribute 'strip'

**Comment by clive7391** [comment]
Thanks for this!
You just cut down a lot of work for me by finding a place to start.
}Invoke-Mimikatz -DumpCreds;
